name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job para rodar os testes em paralelo
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Divisão em 3 partes para execução paralela de testes
        cypress_version: [latest]  # Cypress sempre será instalado na versão mais recente
    steps:
      # Passo 1: Check-out do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configuração do Node.js (versão 22.14)
      - name: Set up Node.js 22.14
        uses: actions/setup-node@v2
        with:
          node-version: '22.14'  # Versão do Node.js 22.14

      # Passo 3: Instalação das dependências com Yarn
      - name: Install dependencies with Yarn
        run: yarn install  # Usando Yarn para instalar as dependências

      # Passo 4: Instalar a versão mais recente do Cypress
      - name: Install Cypress
        run: yarn add cypress@latest  # Garantindo que a versão mais recente do Cypress será instalada

      # Passo 5: Rodar testes Cypress em paralelo
      - name: Run Cypress tests
        run: |
          npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --parallel --ci-build-id $GITHUB_RUN_ID

      # Passo 6: Notificação de falha para Slack
      - name: Notify failure to Slack
        if: failure()  # Somente será executado se o job falhar
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Cypress tests have failed on the branch: ${{ github.ref }}. Check the details!"
          
  # Job para salvar artefatos (exemplo: relatórios de testes, logs, vídeos, etc.)
  save-artifacts:
    runs-on: ubuntu-latest
    needs: cypress-run  # Esse job depende do job cypress-run
    steps:
      - name: Upload Cypress videos and screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
